#!/usr/bin/env python3
import sys
from PyQt5 import QtCore, QtWidgets, QtGui
from PyQt5.QtCore import Qt, QThreadPool, QRunnable, pyqtSignal, QObject
from PyQt5.QtGui import QPalette, QColor
import yfinance as yf
from qtd3 import Ui_MainWindow          # generated by Qt Designer


# ----------------------------------------------------------------------
# Worker signals
# ----------------------------------------------------------------------
class WorkerSignals(QObject):
    price_result = pyqtSignal(str, float, float, float)               # sym, price, prev, %change
    wms_result   = pyqtSignal(str, float, float, float, float, float, float)
    finished     = pyqtSignal()


# ----------------------------------------------------------------------
# Price-update worker
# ----------------------------------------------------------------------
class PriceUpdateWorker(QRunnable):
    def __init__(self, rows):
        super().__init__()
        self.rows = rows
        self.signals = WorkerSignals()

    def run(self):
        for row in self.rows:
            sym = row[0].text().strip()
            if not sym:
                continue
            try:
                t = yf.Ticker(sym)
                d = t.history(period="2d")
                if len(d) < 2:
                    continue
                price = float(d["Close"].iloc[-1])
                prev  = float(d["Close"].iloc[-2])
                change = ((price - prev) / prev) * 100
                self.signals.price_result.emit(sym, price, prev, change)
            except Exception as e:
                print(f"Error {sym}: {e}")
        self.signals.finished.emit()


# ----------------------------------------------------------------------
# W/M/S worker
# ----------------------------------------------------------------------
class WMSUpdateWorker(QRunnable):
    def __init__(self, rows):
        super().__init__()
        self.rows = rows
        self.signals = WorkerSignals()

    def run(self):
        for row in self.rows:
            sym = row[0].text().strip()
            print(sym)
            if not sym:
                continue
            try:
                t = yf.Ticker(sym)

                # week
                d = t.history(period="1mo")
                w_d = w_p = 0
                if not d.empty:
                    s, e = float(d["Close"].iloc[0]), float(d["Close"].iloc[-1])
                    w_d = e - s
                    w_p = (w_d / s) * 100

                # month
                d = t.history(period="3mo")
                m_d = m_p = 0
                if not d.empty:
                    s, e = float(d["Close"].iloc[0]), float(d["Close"].iloc[-1])
                    m_d = e - s
                    m_p = (m_d / s) * 100

                # semester
                d = t.history(period="6mo")
                s_d = s_p = 0
                if not d.empty:
                    s, e = float(d["Close"].iloc[0]), float(d["Close"].iloc[-1])
                    s_d = e - s
                    s_p = (s_d / s) * 100

                self.signals.wms_result.emit(sym, w_d, w_p, m_d, m_p, s_d, s_p)
            except Exception as e:
                print(f"WMS error {sym}: {e}")
        self.signals.finished.emit()


# ----------------------------------------------------------------------
# Alerts window
# ----------------------------------------------------------------------
class AlertsWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Alerts")
        self.setFixedSize(600, 400)
        self.lst = QtWidgets.QListWidget()
        self.lst.setStyleSheet(
            "QListWidget {background:#2d2d2d; color:#00ff00; font-weight:bold;}"
            "QListWidget::item {padding:6px;}"
        )
        self.setCentralWidget(self.lst)

    def add(self, txt):
        self.lst.addItem(txt)
        self.lst.scrollToBottom()


# ----------------------------------------------------------------------
# Main window
# ----------------------------------------------------------------------
class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setWindowTitle("Ban – Stock Monitor")

        self.stopped   = True
        self.wms_busy  = False
        self.timer     = QtCore.QTimer()
        self.timer.timeout.connect(self.trigger_price_update)
        self.pool      = QThreadPool()

        # ---- control buttons ----
        self.startButton.clicked.connect(self.start_updates)
        self.stopButton.clicked.connect(self.stop_updates)
        self.startButton_2.clicked.connect(self.populate_week_month_semester)
        self.radioButtonAlerts.clicked.connect(self.show_alerts)

        self.progressBar.setRange(0, 1)
        self.progressBar.setTextVisible(False)

        self.startButton.setToolTip("Start live updates (every 60 s)")
        self.stopButton.setToolTip("Stop updates")
        self.startButton_2.setToolTip("Load week / month / semester data")

        # ---- load symbols ----
        self.load_symbols()

        # ---- row list (index 8 = price-button) ----
        self.rows = [
            [self.le1s, self.le1p, self.le1c, self.le1w, self.le1m, self.le1t,
             self.le1f, self.le1l, self.hs1],
            [self.le2s, self.le2p, self.le2c, self.le2w, self.le2m, self.le2t,
             self.le2f, self.le2l, self.hs2],
            [self.le3s, self.le3p, self.le3c, self.le3w, self.le3m, self.le3t,
             self.le3f, self.le3l, self.hs3],
            [self.le4s, self.le4p, self.le4c, self.le4w, self.le4m, self.le4t,
             self.le4f, self.le4l, self.hs4],
            [self.le5s, self.le5p, self.le5c, self.le5w, self.le5m, self.le5t,
             self.le5f, self.le5l, self.hs5],
            [self.le6s, self.le6p, self.le6c, self.le6w, self.le6m, self.le6t,
             self.le6f, self.le6l, self.hs6],
            [self.le7s, self.le7p, self.le7c, self.le7w, self.le7m, self.le7t,
             self.le7f, self.le7l, self.hs7],
            [self.le8s, self.le8p, self.le8c, self.le8w, self.le8m, self.le8t,
             self.le8f, self.le8l, self.hs8],
            [self.le9s, self.le9p, self.le9c, self.le9w, self.le9m, self.le9t,
             self.le9f, self.le9l, self.hs9],
            [self.le10s, self.le10p, self.le10c, self.le10w, self.le10m, self.le10t,
             self.le10f, self.le10l, self.hs10],
            [self.le11s, self.le11p, self.le11c, self.le11w, self.le11m, self.le11t,
             self.le11f, self.le11l, self.hs11],
            [self.le12s, self.le12p, self.le12c, self.le12w, self.le12m, self.le12t,
             self.le12f, self.le12l, self.hs12],
            [self.le13s, self.le13p, self.le13c, self.le13w, self.le13m, self.le13t,
             self.le13f, self.le13l, self.hs13],
            [self.le14s, self.le14p, self.le14c, self.le14w, self.le14m, self.le14t,
             self.le14f, self.le14l, self.hs14],
            [self.le15s, self.le15p, self.le15c, self.le15w, self.le15m, self.le15t,
             self.le15f, self.le15l, self.hs15],
            [self.le16s, self.le16p, self.le16c, self.le16w, self.le16m, self.le16t,
             self.le16f, self.le16l, self.hs16],
            [self.le17s, self.le17p, self.le17c, self.le17w, self.le17m, self.le17t,
             self.le17f, self.le17l, self.hs17],
            [self.le18s, self.le18p, self.le18c, self.le18w, self.le18m, self.le18t,
             self.le18f, self.le18l, self.hs18],
            [self.le19s, self.le19p, self.le19c, self.le19w, self.le19m, self.le19t,
             self.le19f, self.le19l, self.hs19],
            [self.le20s, self.le20p, self.le20c, self.le20w, self.le20m, self.le20t,
             self.le20f, self.le20l, self.hs20],
        ]

        # fill symbols
        for i, s in enumerate(self.symbols):
            if i < len(self.rows):
                self.rows[i][0].setText(s)

        self.alert_win = None

    # ------------------------------------------------------------------
    def load_symbols(self):
        try:
            with open("stocksSymbols", "r") as f:
                self.symbols = [ln.strip() for ln in f if ln.strip()]
        except FileNotFoundError:
            self.symbols = ["AAPL", "GOOGL", "MSFT", "TSLA", "NVDA", "AMZN"]
            print("stocksSymbols missing – using defaults")

    # ------------------------------------------------------------------
    def show_alerts(self):
        if not self.alert_win:
            self.alert_win = AlertsWindow()
        self.alert_win.show()
        self.alert_win.raise_()
        self.alert_win.activateWindow()

    # ------------------------------------------------------------------
    def start_updates(self):
        if not self.stopped:
            return
        self.stopped = False
        self.progressBar.setRange(0, 0)
        self.timer.start(60_000)
        self.trigger_price_update()

    def stop_updates(self):
        self.stopped = True
        self.timer.stop()
        self.progressBar.setRange(0, 1)

    # ------------------------------------------------------------------
    def trigger_price_update(self):
        #print(".")
        if self.stopped:
            return
        w = PriceUpdateWorker(self.rows)
        w.signals.price_result.connect(self.handle_price)
        w.signals.finished.connect(self.price_done)
        self.pool.start(w)

    def price_done(self):
        if not self.stopped:
            self.progressBar.setRange(0, 1)

    # ------------------------------------------------------------------
    def handle_price(self, sym, price, prev, change):
        """Colour **every** price-button that belongs to a symbol."""
        for row in self.rows:
            if row[0].text().strip() != sym:
                continue

            # ---- price button (index 8) ----
            #self.set_button_bg(row[8], change)

            # self.set_button_bg(row[3], change)
            # self.set_button_bg(row[4], change)
            # self.set_button_bg(row[5], change)
            # ---- price label (index 1) – always white ----
            row[1].setStyleSheet("color:white; font-weight:bold;")
            row[1].setText(f"{change:+.2f}%   {price:.2f}$")
            self.set_button_bg(row[1], change)
            # ---- previous close ----
            row[2].setText(f"{prev:.2f}$")

            # ---- alert > 5 % ----
            if abs(change) > 5:
                self.add_alert(f"ALERT: {sym} {change:+.2f}%!")
            break                     # one row per symbol

    # ------------------------------------------------------------------
    def populate_week_month_semester(self):
        if self.wms_busy:
            return
        self.wms_busy = True
        self.startButton_2.setEnabled(False)
        self.startButton_2.setText("Loading…")

        w = WMSUpdateWorker(self.rows)
        w.signals.wms_result.connect(self.handle_wms)
        w.signals.finished.connect(self.wms_done)
        self.pool.start(w)

    def handle_wms(self, sym, w_d, w_p, m_d, m_p, s_d, s_p):
        for r in self.rows:
            if r[0].text().strip() != sym:
                continue
            r[3].setStyleSheet(f"color:{self.col(w_p)};")
            r[3].setText(f"{w_d:+.2f}$   {w_p:+.2f}%")
            r[4].setStyleSheet(f"color:{self.col(m_p)};")
            r[4].setText(f"{m_d:+.2f}$   {m_p:+.2f}%")
            r[5].setStyleSheet(f"color:{self.col(s_p)};")
            r[5].setText(f"{s_d:+.2f}$   {s_p:+.2f}%")
            break

    def wms_done(self):
        self.startButton_2.setEnabled(True)
        self.startButton_2.setText("Update W/M/S")
        self.wms_busy = False

    # ------------------------------------------------------------------
    def col(self, pct):
        if pct > 3:   return "#00ff00"
        if pct > 0:   return "#00cc00"
        if pct == 0:  return "white"
        if pct < -5:  return "#ff0000"
        if pct < -3:  return "#cc0000"
        return "#ffaa00"

    # ------------------------------------------------------------------
    def set_button_bg(self, btn, pct):
        """Background colour for the price-button (hs1…hs20)."""
        styles = {
            "lime":    "background:#00ff00; color:white; border-radius:8px; padding:6px; font-weight:bold;",
            "green":   "background:#00cc00; color:white; border-radius:8px; padding:6px; font-weight:bold;",
            "gray":    "background:#333333; color:white; border-radius:8px; padding:6px;",
            "red":     "background:#ff0000; color:white; border-radius:8px; padding:6px; font-weight:bold;",
            "darkred": "background:#cc0000; color:white; border-radius:8px; padding:6px; font-weight:bold;",
            "orange":  "background:#ffaa00; color:white; border-radius:8px; padding:6px; font-weight:bold;",
        }
        key = ("lime"    if pct > 3 else
               "green"   if pct > 0 else
               "gray"    if pct == 0 else
               "red"     if pct < -5 else
               "darkred" if pct < -3 else
               "orange")
        btn.setStyleSheet(styles[key])

    # ------------------------------------------------------------------
    def add_alert(self, txt):
        if not self.alert_win:
            self.show_alerts()
        self.alert_win.add(txt)


# ----------------------------------------------------------------------
# Application entry point
# ----------------------------------------------------------------------
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle('Fusion')

    # dark palette
    p = QPalette()
    p.setColor(QPalette.Window, QColor(45, 45, 45))
    p.setColor(QPalette.WindowText, Qt.white)
    p.setColor(QPalette.Base, QColor(25, 25, 25))
    p.setColor(QPalette.AlternateBase, QColor(53, 53, 53))
    p.setColor(QPalette.ToolTipBase, Qt.white)
    p.setColor(QPalette.ToolTipText, Qt.white)
    p.setColor(QPalette.Text, Qt.white)
    p.setColor(QPalette.Button, QColor(53, 53, 53))
    p.setColor(QPalette.ButtonText, Qt.white)
    p.setColor(QPalette.BrightText, Qt.red)
    p.setColor(QPalette.Link, QColor(42, 130, 218))
    p.setColor(QPalette.Highlight, QColor(42, 130, 218))
    p.setColor(QPalette.HighlightedText, Qt.black)
    app.setPalette(p)

    # global style – control buttons stay dark, price-buttons are styled in code
    app.setStyleSheet("""
        QPushButton { padding:8px 16px; border-radius:6px; font-weight:bold; min-width:80px; }
        QPushButton:disabled { background:#555; color:#aaa; }
        QProgressBar { border:1px solid #555; border-radius:5px; text-align:center; height:20px; }
        QProgressBar::chunk { background:#42a5f5; border-radius:4px; }
        QLabel { font-size:10pt; }
    """)

    win = MainWindow()
    win.show()
    sys.exit(app.exec_())